name: TESTXDC
favicon: null
layout_spectrum: 0.50417
typography_spectrum: 0.14357
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#181818'
    - '#f90d1b'
    - '#d9d0d0'
    - '#838383'
  brandStrength: 0.4375
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
