name: TESTXDC
favicon: null
layout_spectrum: 0.10670960345305502
typography_spectrum: 0.9574225062970072
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.8323682779446244
  lightness: 0.10810539941303432
  saturation: 0.42026153113693
  rhythmicContrast: 0.39668987574987113
purpose: []
